Feature 97 card hand
tpgame-spbstu/Tabletop-roguelike pull request #166
Opened 2022-04-28 23:10 UTC by lyphrowny

Минимально работающая реализация руки карт

Known issues:
- [ ] смена наведенной карты на карту под ней при перспективе
- [ ] близость к ub при несовпадении областей столкновений наведенной \ ненаведенной карт
- [ ] анимация при наведении нечувствительна к расположению камеры (карта выдвигается вверх, не вблизь к камере)
- [ ] отсутствуют анимации передвижения карты при ее добавлении \ удалении
- [ ] на добавление карты при проигрывании анимации наведения на другой карте, другая карта возвращается в предписанную анимацией позицию, хотя она изменилась с добавлением карты

2022-04-28 23:13 UTC, lyphrowny commented on Modification/hand.gd
> +func add_card(card, animation=null) -> Array:
Должен ли метод возвращать позицию, в которую ставится карта, если было решено отдать проигрывание анимации руке?

2022-04-28 23:13 UTC, lyphrowny commented on Modification/hand.gd
> +func add_cards(cards: Array, animation=null) -> Array:
Должен ли метод возвращать позицию, в которую ставится карта, если было решено отдать проигрывание анимации руке?

2022-05-02 21:18 UTC, lyphrowny commented
Рука заняла свое место.
Во время прохождения игры багов встречено не было, однако еще присутствуют некоторые визуальные недоразумения.

2022-05-03 16:15 UTC, maloxit requested changes
Хотелось бы, чтобы в этом таске пофиксилось отображение карт вверх ногами и анимация задвигания карт (слишком высоко подлетают в начале). После этого, если не будет багов, можно закрывать.

2022-05-03 16:15 UTC, maloxit commented on Fight/Human Player/human_player.gd
> +	hand.remove_card(card_to_play)
Функция `remove_card` выполняет много не очевидных действий, многие из которых вообще её не касаются. Лучше оставить интерфейс ближе к тому, что было: старое положение возвращается явно (но лучше не ноду, а сразу `Transform`); карта только удаляется из контейнера, куда её нужно добавить решается вне функции.

2022-05-03 16:15 UTC, maloxit commented on Fight/Human Player/human_player.gd
> -	hand.remove_hand_cell(hand_cell)
В прошлой реализации ожидалось окончание анимации перед тем как заново равномерно разложить оставшиеся карты. Хотелось бы и здесь такое видеть. Здесь можно вставить вызов перекомпоновки.

2022-05-04 17:10 UTC, maloxit approved these changes

2022-05-04 17:10 UTC, merged