Визуальное сопровожнение наведению на точку локации на карте #146
tpgame-spbstu/Tabletop-roguelike pull request #171
Opened 2022-04-29 18:47 UTC by lyphrowny

2022-04-29 18:55 UTC, maloxit requested changes
Те точки, в которые игрок выбирает пойти прямо сейчас должны подсвечиваться по другому (например ярче чем остальные)

2022-04-29 19:08 UTC, lyphrowny commented
> игрок выбирает пойти прямо
Те, на которые игрок нажал? Выделить нажатие на точку?

2022-04-29 20:05 UTC, maloxit commented
> 

Нет, те на которые он сейчас может нажать.

2022-04-30 20:09 UTC, maloxit requested changes

2022-04-30 20:09 UTC, maloxit commented on Map/map.gd
> +		_points[p].lowlight()
![image](https://user-images.githubusercontent.com/61049974/166121081-bf1459cf-7971-4466-8a38-09bca5791a3e.png)
Ошибка при запуске

2022-05-01 19:22 UTC, lyphrowny commented on Map/map.gd
> +		_points[p].lowlight()
Исправлено в [ba03632](https://github.com/tpgame-spbstu/Tabletop-roguelike/pull/171/commits/ba03632f87bea49d5249cd79a1e1e79536ea9af4)

2022-05-01 22:20 UTC, maloxit approved these changes

2022-05-01 22:20 UTC, merged