Feature 147 mark visited map points
tpgame-spbstu/Tabletop-roguelike pull request #172
Opened 2022-04-30 03:15 UTC by lyphrowny

Не очень понятно, что делать с начальной вершиной, ибо на данный момент флажок поднимается по возвращении из локации. У начальной вершины ее нет. Пока что поднимается сразу же при входе на мапу.

Хотелось сделать флажок и map_point независимыми друг от друга, а также соединить поднятие флажка с сигналом. Если первое было успешно достигнуто, со вторым возникли трудности. Текущая реализация - словарь [map_point]: флажок. 

У непосещенной вершины есть флагшток, по которой поднимается флажок, когда вершина становится посещенной. В принципе, флагшток можно начать показывать лишь тогда, когда будет подниматься флажок.

2022-04-30 20:16 UTC, maloxit commented
Мне кажется это разделение здесь совсем не нужно, так как флаг явно относится к map_point, только линшие усложнения. По функционалу нормально, но стоит всё же отображать флагштоки только перед подъемом флага. Ещё стоит задуматься о том, как сохранять поднятые флаги после загрузки игры. Будет логично добавить в map_point_config логический параметр, о том, пройдена ли локация. Это поможет и в последующей реализации выхода в меню, без отката к выбору пути.

2022-04-30 20:39 UTC, maloxit requested changes
Мне кажется это разделение здесь совсем не нужно, так как флаг явно относится к map_point, только линшие усложнения. По функционалу нормально, но стоит всё же отображать флагштоки только перед подъемом флага. Ещё стоит задуматься о том, как сохранять поднятые флаги после загрузки игры. Будет логично добавить в map_point_config логический параметр, о том, пройдена ли локация. Это поможет и в последующей реализации выхода в меню, без отката к выбору пути.

2022-04-30 20:44 UTC, lyphrowny commented
> так как флаг явно относится к map_point

Согласен с одной стороны, с другой, флажок не имеет смысла без мапы, поэтому было принято сохранить чистоту map_point. Можно, конечно, отнаследоваться от map_point и добавить флажок, чтобы получился map_point с флажочком. Чувствую, на архитектора нужно было идти...

> отображать флагштоки только перед подъемом флага

Не будет ли тогда непонятно, откуда взялась палка, и почему по ней поднимается флаг? Ы, а так получается непонятно, что за палка стоит на map_point, да? Хотя, флажок на первом map_point должен прояснить неясность

Сохранение состояния принял, будет.

2022-04-30 20:57 UTC, maloxit commented
> с другой, флажок не имеет смысла без мапы

Так-то и map_point не имеет смысла без мапы, так что тут всё нормально.

> , поэтому было принято сохранить чистоту map_point

Наследование в ООП это такая вещь, в которой можно запутаться и начать переписывать архитектуру ради наследования всего и вся, когда это совершенно не нужно. Пока архитектура не предусматривает нескольких вариантов использования map_point с общим функционалом, не надо городить наследование. Когда такая последовательность появится, тогда и сделаем.

> Не будет ли тогда непонятно, откуда взялась палка

Не будет) Можно добавить анимацию поднятия палки.

2022-05-01 23:16 UTC, lyphrowny commented
- добавил анимацию появления флагштока
- добавил флажок посещенности в map_point_config. map_config хранит массив посещенных map_point'ов (1)
- добавил флажок необходимости анимации баннера

(1) \- нужно ли это? Достаточно будет пробежаться по map_point (map_point_config), чтобы узнать статус этого флажка у каждой сущности

2022-05-01 23:19 UTC, maloxit commented
> (1) - нужно ли это? Достаточно будет пробежаться по map_point (map_point_config), чтобы узнать статус этого флажка у каждой сущности

2022-05-02 13:28 UTC, maloxit approved these changes

2022-05-02 13:30 UTC, maloxit commented
@lyphrowny разреши конфликты слияния

2022-05-03 16:27 UTC, merged