Feature 149 return to main menu and small improvements
tpgame-spbstu/Tabletop-roguelike pull request #179
Opened 2022-05-05 17:27 UTC by maloxit

Добавление возврата в меню потребовало смежных изменений:
- [ ] Кнопка возврата в меню
- [ ] Поменял логику работы кнопок "продолжить" и "новая игра" в главном меню - теперь загрузка из файла происходит при запуске игры, "новая игра" заново генерирует game_config, "продолжить" - активна, если уже сгенерирован game_config, просто загружает его.
- [ ] Перед попаданием в локацию нужно нажать кнопку "исследовать". Это позволяет не сбрасывать выбор пути при возврате в меню, если игрок ещё не прошел локацию.
- [ ] Изменил алгоритм перекрашивания недоступных путей, так как старый

Помимо этого, позволил себе некоторые улучшения и багфиксы.
- [ ] Большая часть анимации заменена на сглаженную версию, на мапе без неё выглядело не очень.
- [ ] Исправил ошибки в лейблах настроек громкости
- [ ] Включил у путей прозрачность, стало выглядеть лучше
- [ ] Подправил камеру и украшения на мапе
- [ ] Изменил не активный цвет выделения точки на карте, чтобы не сливалось с путями

2022-05-05 20:41 UTC, lyphrowny approved these changes
Сделать кнопку "Исследовать" как контекстное меню при наведении мыши на map_point?

2022-05-08 19:16 UTC, ayu-f commented
Предлагаю когда персонаж находится на точке локации, но ее еще не исследовал, убирать крутящийся спрайт
Иначе когда добавим персонажа будет накладываться все

2022-05-08 19:47 UTC, lyphrowny requested changes
- ругается на анимацию над точкой
![Screenshot from 2022-05-08 22-30-29](https://user-images.githubusercontent.com/79705170/167312811-df6d765d-a4eb-422d-b42a-8424d7363ad3.png)
- при движении к точке пропадает ее выделение, но по прибытии точка является выделенной (зеленой), хотя мышь вне точки. При любом движении мыши цвет выделения меняется на белый. Не выделять зеленым?

2022-05-08 19:47 UTC, lyphrowny commented on Map/map.gd
> +func set_moving_state():
метод является внутренним
```suggestion
func _set_moving_state():
```

2022-05-08 19:47 UTC, lyphrowny commented on Map/map.gd
> +func set_moving_state():
Другие, изменяющие state, тоже

2022-05-08 19:52 UTC, lyphrowny commented
Когда пришел в точку, не понял, что делать дальше: ну, пришел и пришел, а дальше-то что? Кнопка посередине экрана была более информативной... Кажется, нужно либо ее вернуть, либо добавить всплывающую подсказку а-ля туториал: "Теперь надо исследовать локацию".

2022-05-08 19:57 UTC, lyphrowny commented on Map/map.gd
>  var _paths = Dictionary()
Переменная `_graph` не используется

2022-05-09 21:57 UTC, merged