Добавил иконки на мапу, немного изменил саму мапу
tpgame-spbstu/Tabletop-roguelike pull request #180
Opened 2022-05-05 21:04 UTC by ayu-f

Добавил еще немного ассетов на мапу, да и в принципе можно будет потом еще подобавлять из папки

2022-05-05 21:44 UTC, lyphrowny requested changes

2022-05-05 21:44 UTC, lyphrowny commented on Map/Location/map_point.gd
> +var is_not_visited = true
В map_point_config есть флажок, отвечающий за посещенность map_point + его сеттер и геттер

2022-05-05 21:44 UTC, lyphrowny commented on Map/Location/map_point_config.gd
> +enum types_map {MOD, FIGHT}
```suggestion
enum {MOD, FIGHT}
```
Сделать безымянным, тогда можно будет обращаться напрямую `MapPointConfig.MOD` (предложение)

2022-05-06 15:13 UTC, ayu-f commented on Map/Location/map_point_config.gd
> +enum types_map {MOD, FIGHT}
Тут дело вкуса, безымянный enum это по факту две const будут, а с именем какая-то структурированность появляется (хотя на самом деле не совсем)

2022-05-06 16:15 UTC, lyphrowny approved these changes

2022-05-06 16:15 UTC, lyphrowny commented on Map/Location/map_point.gd
> +	if not map_point_config._is_visited:
```suggestion
	if not map_point_config.is_visited():
```
Вместо обращения к атрибуту использовать его геттер

2022-05-07 21:30 UTC, maloxit commented
![image](https://user-images.githubusercontent.com/61049974/167271877-6ea7fcd7-9d58-4f73-98ee-ecfb11d84f48.png)
Касательно сцены <map_point>:

- [ ] В <CollisionShape> поменять меш на цилиндр по размеру платформы
- [ ] <on_hover_mesh1> нигде не используется, удалить
- [ ] <MeshInstance> тоже не видно. Удалить, выкорчевать всё что касается его текстур в коде (в <map_point_config.gd>, <map_point.gd> и <game_load_manager.gd>)
- [ ] Вместо того, чтобы в коде вращать <sprite_type>, лучше накинуть на него <AnimationPlayer> и добавить зацикленную анимацию покачивания, чтобы не было такого, что она встаёт боком к камере.

2022-05-08 17:50 UTC, merged